openapi: 3.0.0
info:
  title: FitBook API
  description: Documentazione Swagger per le API del sistema di prenotazione corsi, acquisto abbonamenti, login/registrazione.
  version: 1.0.0
servers:
  - url: https://fitbook-sr59.onrender.com
components:
  parameters:
    UserAgentHeader:
      name: User-Agent
      in: header
      required: true
      schema:
        type: string
        default: SwaggerClient/1.0
paths:
  /register:
    post:
      summary: Registra un nuovo utente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                birthdate:
                  type: string
                  format: date
                password:
                  type: string
      responses:
        '201':
          description: Utente registrato con successo
  /login:
    post:
      summary: Effettua il login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login effettuato con successo
  /retrieveCourse:
    get:
      summary: Recupera i corsi prenotabili per un utente
      parameters:
        - in: query
          name: userEmail
          required: true
          schema:
            type: string
          description: Nome dell'utente per cui recuperare i corsi prenotabili
        - in: query
          name: reservation_date
          required: true
          schema:
            type: string
            format: date
          description: Data della prenotazione per cui recuperare i corsi
      responses:
        '200':
          description: Lista dei corsi disponibili
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    courseId:
                      type: string
                      description: ID del corso
                    courseName:
                      type: string
                      description: Nome del corso
                    availableSeats:
                      type: integer
                      description: Numero di posti disponibili
  /confirmedReservation:
    post:
      summary: Conferma una prenotazione
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                courseId:
                  type: integer
                reservationDate:
                  type: string
                  format: date
                reservation_status:
                  type: string
      responses:
        '200':
          description: Prenotazione confermata
  /retrieveReservation:
    post:
      summary: Recupera le prenotazioni di un utente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
      responses:
        '200':
          description: Lista delle prenotazioni
  /deleteReservation:
    post:
      summary: Elimina una prenotazione
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                reservationId:
                  type: integer
      responses:
        '200':
          description: Prenotazione eliminata
  /buySubription:
    post:
      summary: Acquista un abbonamento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                subscription:
                  type: integer
      responses:
        '200':
          description: Abbonamento acquistato
  /retrieveSubscription:
    post:
      summary: Recupera l'abbonamento di un utente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
      responses:
        '200':
          description: Dettagli dell'abbonamento
